"use server";

import nodemailer from "nodemailer";

export async function submitContactForm(prevState: any, formData: FormData) {
  const firstName = formData.get("firstName") as string;
  const lastName = formData.get("lastName") as string;
  const email = formData.get("email") as string;
  const company = formData.get("company") as string;
  const message = formData.get("message") as string;

  // Basic validation
  if (!firstName || !lastName || !email || !message) {
    return {
      success: false,
      error: true,
      message: "Please fill in all required fields.",
    };
  }

  const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
  if (!emailRegex.test(email)) {
    return {
      success: false,
      error: true,
      message: "Please enter a valid email address.",
    };
  }

  try {
    const transporter = nodemailer.createTransport({
      host: process.env.EMAIL_HOST,
      port: Number(process.env.EMAIL_PORT),
      secure: process.env.EMAIL_SECURE === "true",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
      authMethod: "PLAIN",
      tls: {
        // Do not fail on invalid certs (common for cPanel self-signed certs)
        rejectUnauthorized: false,
      },
    });

    const mailOptions = {
      from: `"Procobiz Contact Form" <${process.env.EMAIL_USER}>`,
      replyTo: `${firstName} ${lastName} <${email}>`,
      to: process.env.EMAIL_TO,
      subject: `📨: New Submission from ${firstName} ${lastName}`,
      html: `
  <div style="
    font-family: Arial, sans-serif;
    background-color: #f4f8ff;
    padding: 20px;
  ">
    <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.05);">
      <tr>
        <td style="background-color: #007BFF; padding: 20px; text-align: center; color: #ffffff;">
          <img src="https://procobiz.com/procobiz-logo-black.png" alt="Procobiz Logo" style="height: 40px; margin-bottom: 8px;" />
          <h1 style="margin: 0; font-size: 20px;">New Message 📨</h1>
        </td>
      </tr>
      <tr>
        <td style="padding: 20px; color: #333333;">
          <p style="margin: 0 0 10px 0;"><strong>Sender:</strong> ${firstName} ${lastName}</p>
          <p style="margin: 0 0 10px 0;"><strong>Email:</strong> <a href="mailto:${email}" style="color: #007BFF;">${email}</a></p>
          <p style="margin: 0 0 10px 0;"><strong>Company:</strong> ${
            company || "N/A"
          }</p>
          <hr style="border: none; border-top: 1px solid #e0e0e0; margin: 20px 0;" />
          <p style="margin-bottom: 5px;"><strong>Message:</strong></p>
          <div style="white-space: pre-wrap; line-height: 1.6; background-color: #f9fbff; padding: 10px 15px; border-radius: 6px; border: 1px solid #e8efff;">
            ${message}
          </div>
        </td>
      </tr>
      <tr>
        <td style="background-color: #f1f5ff; text-align: center; padding: 15px; font-size: 12px; color: #555;">
          <p style="margin: 0;">Sent on ${new Date().toLocaleString()}</p>
          <p style="margin: 5px 0 0 0;">This email was automatically generated by your website's contact form.</p>
        </td>
      </tr>
    </table>
  </div>
  `,
    };

    const feedbackOptions = {
      from: `"Procobiz" <${process.env.EMAIL_USER}>`,
      to: email,
      subject: "We’ve received your message — Procobiz Support",
      html: `
  <div style="
    font-family: Arial, sans-serif;
    background-color: #f4f8ff;
    padding: 20px;
  ">
    <table width="100%" cellpadding="0" cellspacing="0" style="max-width: 600px; margin: 0 auto; background: #ffffff; border-radius: 10px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.05);">
      <tr>
        <td style="background-color: #007BFF; padding: 20px; text-align: center; color: #ffffff;">
          <img src="https://procobiz.com/procobiz-logo-black.png" alt="Procobiz Logo" style="height: 40px; margin-bottom: 8px;" />
          <h2 style="margin: 0; font-size: 20px;">Thank you for contacting Procobiz</h2>
        </td>
      </tr>
      <tr>
        <td style="padding: 20px; color: #333;">
          <p>Hi ${firstName},</p>
          <p>We’ve received your message and our team will review it shortly. You can expect a response within 24 hours.</p>
          <p style="margin-top: 20px;">Here’s a copy of what you sent us:</p>
          <div style="white-space: pre-wrap; line-height: 1.6; background-color: #f9fbff; padding: 10px 15px; border-radius: 6px; border: 1px solid #e8efff;">
            ${message}
          </div>
          <p style="margin-top: 25px; color: #555;">Kind regards,<br><strong>The Procobiz Team</strong></p>
        </td>
      </tr>
      <tr>
        <td style="background-color: #f1f5ff; text-align: center; padding: 15px; font-size: 12px; color: #555;">
          <p style="margin: 0;">This is an automated confirmation. Please do not reply directly to this email.</p>
        </td>
      </tr>
    </table>
  </div>
  `,
    };

    await transporter.sendMail(mailOptions);
    // Send confirmation email to the sender
    await transporter.sendMail(feedbackOptions);

    return {
      success: true,
      error: false,
      message: "Your message has been sent successfully!",
    };
  } catch (error) {
    console.error("Email sending failed:", error);
    return {
      success: false,
      error: true,
      message:
        "Something went wrong while sending your message. Please try again later.",
    };
  }
}
